name: Continuous Deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Everything
    steps:
      - name: Save pem key
        run: |
          echo "${{secrets.SSH_SECRET}}" &> key.pem
          chmod 600 key.pem
          head -3 key.pem

      - name: Deploy to EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@"${{secrets.EC2_IP}}" -t "cd /home/ubuntu/Draw-app && git pull origin main && pnpm run build && pm2 restart all"
